[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smart-file-sync"
version = "0.1.0"
description = "A lightweight Python utility for safely synchronizing files between two directories."
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.10"
authors = [
    { name = "yaniishsn" },
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
]

[project.scripts]
smart-file-sync = "smart_file_sync.main:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
